# Generated by Django 3.2.4 on 2021-06-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_alter_mobi_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobi',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mobi',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
